// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF4huKeAbiKBvMUFo4728jxed40zBhHc4',
    appId: '1:876956357109:web:7cf276e21ce6a4ac0c10bc',
    messagingSenderId: '876956357109',
    projectId: 'ecommerce-app-789b6',
    authDomain: 'ecommerce-app-789b6.firebaseapp.com',
    storageBucket: 'ecommerce-app-789b6.appspot.com',
    measurementId: 'G-1JMD92F8YR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh1Qvj9r1BEAvxEUk9z4BJezblGSJIThM',
    appId: '1:876956357109:android:5f15572b9b2a4ade0c10bc',
    messagingSenderId: '876956357109',
    projectId: 'ecommerce-app-789b6',
    storageBucket: 'ecommerce-app-789b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJHrTlXKHcCWB4B2PDktaPz5Xy6T_GXFc',
    appId: '1:876956357109:ios:6dfb288ff7e939050c10bc',
    messagingSenderId: '876956357109',
    projectId: 'ecommerce-app-789b6',
    storageBucket: 'ecommerce-app-789b6.appspot.com',
    iosBundleId: 'com.example.eccomerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJHrTlXKHcCWB4B2PDktaPz5Xy6T_GXFc',
    appId: '1:876956357109:ios:b164790aef76b5e50c10bc',
    messagingSenderId: '876956357109',
    projectId: 'ecommerce-app-789b6',
    storageBucket: 'ecommerce-app-789b6.appspot.com',
    iosBundleId: 'com.example.eccomerceApp.RunnerTests',
  );
}
